#!/bin/bash
./extract-entries /mnt/storage/cc/CC-MAIN-20181113000225-20181113022225-00331.warc.gz 5000
rm -rf entries-samples
cp -ar entries entries-samples
for x in entries-samples/*; do
  head -c10000 "$x" > x
  mv x "$x"
done
