#!/bin/bash

set -eu

usage() {
  (
  cat <<EOF
usage: $0 <warc-archive> [number-records]
  warc-archive can be a local file or an HTTPS file
  number-records is the number of records to extract; or all if absent

Records are placed in the records directory.
EOF
  ) > /dev/stderr
}

main() {
  if [ "$#" == "0" ]; then
    usage
    exit 2
  fi

  file=${1:?must specify WARC archive, either local file or http URL}
  entries=${2:-999999}

  rm -rf entries
  mkdir entries
  zcat "$1" |
    awk -v entries="$entries" '
    BEGIN { n = 0 }
    /^WARC\/1.0/ { n = n + 1; close(f); f = sprintf("entries/%06d", n); if (n > entries) { exit 0 } }
    { print >> f }
    END { close(f) }
    '
}

main "$@"
